#define M_HORSE_1 "/wiz/ljty/modules/m_horse.c"
#define L_LOCKABLE "/wiz/ljty/obj/door/l_lockable.c"
#define CHENGMEN_ROOM "/wiz/ljty/modules/chengmen_room.c"
#define INDOOR_ROOM_TYPE 1
#define M_USEABLE "/wiz/ljty/modules/m_useable.c"
#define L_SECRET_DOOR "/wiz/ljty/obj/door/l_secret_door.c"
#define L_HIDDEN_DOOR "/wiz/ljty/obj/door/l_hidden_door.c"
#define L_DOOR "/wiz/ljty/obj/door/l_door.c"
#define M_VALUE "/sgdomain/modules/m_value.c"
